# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 62a42618be976e2f0939c779fa8491b90e7abc35cafc8e8ec68827430c66ab916e51d5689afd0a3801a2b5ed0e9e2e03c79f8d6fc5bfa62b87a4b3f9cb2ef710

test:
  secret_key_base: 73f0ef4aa08d123d927a1e1e1b7fde565f5f04a2f43125c75d87c588b6de86d2f2dcbce7c57e3b81f3b1e772badac692411019df940b561e46217c1f5e1b5e38

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
